const queue = new akutil.Queue()
queue.print()
console.log(queue.isEmpty())
queue.enqueue(1)
queue.enqueue(2)
queue.enqueue(3)
queue.print()
console.log(queue.isEmpty())
console.log(queue.front())
console.log(queue.dequeue())
console.log(queue.dequeue())
console.log(queue.dequeue())
console.log(queue.dequeue())
console.log(queue.dequeue())
queue.enqueue(3)
console.log(queue.front())

console.log('========优先队列')
// 优先队列
const priorityQueue = new akutil.PriorityQueue()
priorityQueue.print()
priorityQueue.enqueue('b')
priorityQueue.enqueue('c')
priorityQueue.enqueue('d')
priorityQueue.print()
console.log(priorityQueue.front())
priorityQueue.enqueue('a', 2)
console.log(priorityQueue.front())
priorityQueue.enqueue('e', 2)
priorityQueue.enqueue('f')
priorityQueue.enqueue('g')
priorityQueue.enqueue('h', 2)
priorityQueue.enqueue('A', 3)
priorityQueue.enqueueByMin('m', 4)
priorityQueue.enqueueByMin('mn', 3)
console.log(priorityQueue.front())
priorityQueue.print()

console.log('=======循环队列')
const cycleQueue = new akutil.CycleQueue(3)
console.log(cycleQueue.enqueue(3))
console.log(cycleQueue.enqueue(2))
console.log(cycleQueue.toString())
console.log('isFull', cycleQueue.isFull())
console.log(cycleQueue.enqueue(1))
console.log(cycleQueue.toString())
console.log('size', cycleQueue.size())
console.log(cycleQueue.toString())
console.log(cycleQueue.enqueue(0))
console.log('size', cycleQueue.size())
console.log(cycleQueue.peek())
console.log(cycleQueue.enqueue(1))
console.log(cycleQueue.toString())
console.log(cycleQueue.dequeue())
console.log(cycleQueue.peek())
console.log(cycleQueue.toString())
console.log(cycleQueue.dequeue())
console.log(cycleQueue.toString())
console.log(cycleQueue.dequeue())
