const stack = new akutil.Stack()
stack.print()
console.log(stack.isEmpty())
stack.push(1)
stack.push(2)
stack.push(3)
stack.print()
console.log(stack.isEmpty())
console.log(stack.peek())
console.log(stack.pop())
console.log(stack.peek())
